-- 000001_init_schema.down.sql
-- 初期スキーマの全テーブルを削除する

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `ai_generated_questions`;
DROP TABLE IF EXISTS `ai_question_templates`;
DROP TABLE IF EXISTS `analysis_phases`;
DROP TABLE IF EXISTS `anonymized_behavior_summaries`;
DROP TABLE IF EXISTS `api_call_logs`;
DROP TABLE IF EXISTS `audit_logs`;
DROP TABLE IF EXISTS `chat_messages`;
DROP TABLE IF EXISTS `collective_insight_logs`;
DROP TABLE IF EXISTS `companies`;
DROP TABLE IF EXISTS `company_benefits`;
DROP TABLE IF EXISTS `company_job_positions`;
DROP TABLE IF EXISTS `company_market_info`;
DROP TABLE IF EXISTS `company_popularity_records`;
DROP TABLE IF EXISTS `company_profile_update_histories`;
DROP TABLE IF EXISTS `company_relations`;
DROP TABLE IF EXISTS `company_reviews`;
DROP TABLE IF EXISTS `company_weight_profiles`;
DROP TABLE IF EXISTS `conversation_contexts`;
DROP TABLE IF EXISTS `crawl_runs`;
DROP TABLE IF EXISTS `crawl_sources`;
DROP TABLE IF EXISTS `g_biz_company_profiles`;
DROP TABLE IF EXISTS `g_biz_finances`;
DROP TABLE IF EXISTS `g_biz_procurements`;
DROP TABLE IF EXISTS `g_biz_subsidies`;
DROP TABLE IF EXISTS `g_biz_workplaces`;
DROP TABLE IF EXISTS `git_hub_language_stats`;
DROP TABLE IF EXISTS `git_hub_profiles`;
DROP TABLE IF EXISTS `git_hub_repo_summaries`;
DROP TABLE IF EXISTS `git_hub_repos`;
DROP TABLE IF EXISTS `graduate_employments`;
DROP TABLE IF EXISTS `industries`;
DROP TABLE IF EXISTS `industry_job_categories`;
DROP TABLE IF EXISTS `interview_company_questions`;
DROP TABLE IF EXISTS `interview_question_states`;
DROP TABLE IF EXISTS `interview_reports`;
DROP TABLE IF EXISTS `interview_sessions`;
DROP TABLE IF EXISTS `interview_utterances`;
DROP TABLE IF EXISTS `interview_videos`;
DROP TABLE IF EXISTS `job_categories`;
DROP TABLE IF EXISTS `job_category_embeddings`;
DROP TABLE IF EXISTS `pending_registrations`;
DROP TABLE IF EXISTS `predefined_questions`;
DROP TABLE IF EXISTS `question_variants`;
DROP TABLE IF EXISTS `question_weights`;
DROP TABLE IF EXISTS `realtime_usage_logs`;
DROP TABLE IF EXISTS `resume_documents`;
DROP TABLE IF EXISTS `resume_review_items`;
DROP TABLE IF EXISTS `resume_reviews`;
DROP TABLE IF EXISTS `resume_text_blocks`;
DROP TABLE IF EXISTS `schedule_events`;
DROP TABLE IF EXISTS `score_calibration_weights`;
DROP TABLE IF EXISTS `scraper_sessions`;
DROP TABLE IF EXISTS `session_validations`;
DROP TABLE IF EXISTS `skill_scores`;
DROP TABLE IF EXISTS `user_analysis_progress`;
DROP TABLE IF EXISTS `user_application_statuses`;
DROP TABLE IF EXISTS `user_company_matches`;
DROP TABLE IF EXISTS `user_embeddings`;
DROP TABLE IF EXISTS `user_google_tokens`;
DROP TABLE IF EXISTS `user_weight_scores`;
DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `variant_assignments`;
DROP TABLE IF EXISTS `weight_rules`;

SET FOREIGN_KEY_CHECKS = 1;
